### ISSUE TITLE
naiverproxy建议加入如下参数，缓解断流

### ISSUE THREAD

**Issue by Pacio** [maidoudouo/XRay_Trojan_Naiveproxy_Docker#1]
{
  "listen": "socks://127.0.0.1:1080",
  "proxy": "https://a:b@c.com",
  "concurrency": "2"
}

**Comment by asushugo** [comment]
这段东西是加在客户端的，而不是服务端
参考https://github.com/klzgrad/naiveproxy#client-setup

**Comment by maidoudouo** [comment]
这段东西是加在客户端的，而不是服务端
参考https://github.com/klzgrad/naiveproxy#client-setup
